version: "3.7"

services:
  postgres:
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASS}"
    ports:
      - ${LOCAL_PORT}:${DOCKER_PORT}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    command: python3 main.py
    env_file:
      - .env
    volumes:
      - .:/api_db/
    ports:
      - 8008:8000
    depends_on:
      postgres:
        condition: service_healthy